services:
  order-service:
    build: .
    container_name: order-service
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=reactive-docker
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbit
      - SPRING_RABBITMQ_PASSWORD=rabbit
      - SPRING_DATA_REDIS_HOST=redis-service
    networks:
      - stock_exchange_network

  postgres:
    image: postgres:17
    container_name: order-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5432"
    networks:
      - stock_exchange_network

  redis:
    image: redis:7-alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - stock_exchange_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    networks:
      - stock_exchange_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - stock_exchange_network

  kafka:
    image: apache/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - stock_exchange_network
    volumes:
      - ./kafka-data:/var/lib/kafka/data

networks:
  stock_exchange_network:
    external: true

volumes:
  postgres_data:
  kafka-data: