spring.application.name=order-service
server.port=8081
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:app.pub

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.r2dbc.pool.max-size=100

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleOrder;handleTrade

#spring.cloud.stream.bindings.tradingEvents-out-0.content-type=application/json
#spring.cloud.stream.rabbit.bindings.tradingEvents-out-0.producer.exchange-type=topic
#spring.cloud.stream.bindings.handleOrder-in-0.destination=orders.updated
#spring.cloud.stream.bindings.handleOrder-in-0.group=order-service-queue
#spring.cloud.stream.bindings.handleTrade-in-0.destination=trades.executed
#spring.cloud.stream.bindings.handleTrade-in-0.group=trade-service-queue

#kafka


spring.cloud.stream.bindings.handleOrder-in-0.destination=orders.updated
spring.cloud.stream.bindings.handleOrder-in-0.group=order-service-kafka
spring.cloud.stream.kafka.bindings.handleOrder-in-0.consumer.startOffset=latest
spring.cloud.stream.kafka.bindings.handleOrder-in-0.consumer.resetOffsets=true

spring.cloud.stream.bindings.handleTrade-in-0.destination=trades.executed
spring.cloud.stream.bindings.handleTrade-in-0.group=trade-service-kafka
spring.cloud.stream.kafka.bindings.handleTrade-in-0.consumer.startOffset=latest
spring.cloud.stream.kafka.bindings.handleTrade-in-0.consumer.resetOffsets=true
spring.cloud.stream.kafka.binder.autoAddPartitions=true