spring.application.name=order-service
server.port=8081
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:app.pub

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.r2dbc.pool.max-size=100

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleTrade;handleOrderRejected;handleOrderUpdate;onPortfolioResponse

spring.cloud.stream.bindings.portfolioCommands-out-0.destination=portfolio.commands
spring.cloud.stream.rabbit.bindings.portfolioCommands-out-0.producer.routingKeyExpression=headers['eventType']


spring.cloud.stream.bindings.handleOrderUpdate-in-0.destination=order.events
spring.cloud.stream.bindings.handleOrderUpdate-in-0.group=order-update-queue
spring.cloud.stream.rabbit.bindings.handleOrderUpdate-in-0.consumer.bindingRoutingKey=order.updated
spring.cloud.stream.rabbit.bindings.handleOrderUpdate-in-0.consumer.exchangeType=topic

spring.cloud.stream.bindings.handleOrderRejected-in-0.destination=order.events
spring.cloud.stream.bindings.handleOrderRejected-in-0.group=order-reject-queue
spring.cloud.stream.rabbit.bindings.handleOrderRejected-in-0.consumer.bindingRoutingKey=order.rejected
spring.cloud.stream.rabbit.bindings.handleOrderRejected-in-0.consumer.exchangeType=topic

spring.cloud.stream.bindings.handleOrderRejected-out-0.destination=portfolio.commands
spring.cloud.stream.rabbit.bindings.handleOrderRejected-out-0.producer.routingKeyExpression=headers['eventType']


spring.cloud.stream.bindings.handleTrade-in-0.destination=trade.events
spring.cloud.stream.bindings.handleTrade-in-0.group=trade-service-queue
spring.cloud.stream.rabbit.bindings.handleTrade-in-0.consumer.bindingRoutingKey=trade.executed
spring.cloud.stream.rabbit.bindings.handleTrade-in-0.consumer.exchangeType=topic

spring.cloud.stream.bindings.handleTrade-out-0.destination=portfolio.commands
spring.cloud.stream.rabbit.bindings.handleTrade-out-0.producer.routingKeyExpression=headers['eventType']


spring.cloud.stream.bindings.onPortfolioResponse-in-0.destination=portfolio.responses
spring.cloud.stream.bindings.onPortfolioResponse-in-0.group=order-saga-queue

spring.cloud.stream.bindings.onPortfolioResponse-out-0.destination=match.commands

#kafka
#spring.kafka.bootstrap-servers=localhost:9092
#spring.cloud.stream.bindings.orderEvents-out-0.destination=order.events
#
#spring.cloud.stream.bindings.handleOrderUpdate-in-0.destination=order.events
#spring.cloud.stream.bindings.handleOrderUpdate-in-0.group=order-updated-group
#spring.cloud.stream.kafka.bindings.handleOrderUpdate-in-0.consumer.startOffset=latest
#spring.cloud.stream.kafka.bindings.handleOrderUpdate-in-0.consumer.resetOffsets=true
#
#spring.cloud.stream.bindings.handleOrderRejected-in-0.destination=order.events
#spring.cloud.stream.bindings.handleOrderRejected-in-0.group=order-rejected-group
#spring.cloud.stream.kafka.bindings.handleOrderRejected-in-0.consumer.startOffset=latest
#spring.cloud.stream.kafka.bindings.handleOrderRejected-in-0.consumer.resetOffsets=true
#
#spring.cloud.stream.bindings.handleTrade-in-0.destination=trade.events
#spring.cloud.stream.bindings.handleTrade-in-0.group=trade-executed-group
#spring.cloud.stream.kafka.bindings.handleTrade-in-0.consumer.startOffset=latest
#spring.cloud.stream.kafka.bindings.handleTrade-in-0.consumer.resetOffsets=true
#
#spring.cloud.stream.bindings.handleBalance-in-0.destination=portfolio.events
#spring.cloud.stream.bindings.handleBalance-in-0.group=order-balance-group
#spring.cloud.stream.kafka.bindings.handleBalance-in-0.consumer.startOffset=latest
#spring.cloud.stream.kafka.bindings.handleBalance-in-0.consumer.resetOffsets=true
#spring.cloud.stream.kafka.binder.autoAddPartitions=true

