spring.application.name=order-service
server.port=8081
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:app.pub

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.r2dbc.pool.max-size=100

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleOrder;handleTrade

spring.cloud.stream.bindings.tradingEvents-out-0.destination=trading.events
spring.cloud.stream.bindings.tradingEvents-out-0.content-type=application/json
spring.cloud.stream.rabbit.bindings.tradingEvents-out-0.producer.exchange-type=topic
spring.cloud.stream.rabbit.bindings.tradingEvents-out-0.producer.routing-key-expression=headers['type']

spring.cloud.stream.bindings.handleOrder-in-0.destination=trading.events
spring.cloud.stream.bindings.handleOrder-in-0.group=order-service-queue
spring.cloud.stream.rabbit.bindings.handleOrder-in-0.consumer.binding-routing-key=orders.updated

spring.cloud.stream.bindings.handleTrade-in-0.destination=trading.events
spring.cloud.stream.bindings.handleTrade-in-0.group=trade-service-queue

spring.cloud.stream.rabbit.bindings.handleTrade-in-0.consumer.binding-routing-key=trades.executed
